#!/bin/bash
#PBS -A colosse-users
#PBS -l nodes=1:gpus=1
#PBS -l walltime=43200
#PBS -E
#PBS -e param_search.err
#PBS -o param_search.out


# set the working directory to where the job is launched
cd "${PBS_O_WORKDIR}"

s_exec python -u hyperparameter_search.py --config="logs/CAE_cluster/param_search/config.json" --helios-run="param_search"

mv param_search.err logs/CAE_cluster/param_search/
mv param_search.out logs/CAE_cluster/param_search/
